### ISSUE TITLE
"ls" error while listing SmvDataSet which dsType() is Model/ModelExec

### ISSUE THREAD

**Issue by fei-cheng** [TresAmigosSD/SMV#1010]
The stack track looks like:
<code>
Py4JJavaError: An error occurred while calling z:org.tresamigos.smv.shell.ShellCmd.ls.
: scala.MatchError: ModelExec (of class java.lang.String)
 at org.tresamigos.smv.graph.SmvGraphUtil.org$tresamigos$smv$graph$SmvGraphUtil$$baseNameWithFlag(SmvStageGraph.scala:115)
 at org.tresamigos.smv.graph.SmvGraphUtil$$anonfun$org$tresamigos$smv$graph$SmvGraphUtil$$_listInStage$1.apply(SmvStageGraph.scala:276)
 at org.tresamigos.smv.graph.SmvGraphUtil$
...
</code>

We need to modify the function "baseNameWithFlag" in class **SmvGraphUtil**, choose another flag for Model and ModelExec as "M" was occupied by Module.

**Comment by ninjapapa** [comment]
Fixed.
