### ISSUE TITLE
IsSmvDataSet doesn't work for java object

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1025]
When creates a variable like the following in a core.py file:
```
measureTimePanel = P.TimePanel(P.Month(2015,1), P.Month(2016,12))
```

SMV will raise a strange error like the following,
```
Traceback (most recent call last):
  File "/Users/bzhang/Tresamigos/SMV/src/main/python/smv/py4j_interface.py", line 35, in interface_method
    result = impl_method(*args)
  File "/Users/bzhang/Tresamigos/SMV/src/main/python/smv/datasetrepo.py", line 78, in dataSetsForStage
    return self._moduleUrnsForStage(stageName, lambda obj: obj.IsSmvDataSet)
  File "/Users/bzhang/Tresamigos/SMV/src/main/python/smv/datasetrepo.py", line 108, in _moduleUrnsForStage
    if fn(obj) and obj.fqn().startswith(name) and not inspect.isabstract(obj):
  File "/Users/bzhang/spark-1.5.2/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
    self.target_id, self.name)
  File "/Users/bzhang/spark-1.5.2/python/pyspark/sql/utils.py", line 36, in deco
    return f(*a, **kw)
  File "/Users/bzhang/spark-1.5.2/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 304, in get_return_value
    format(target_id, '.', name, value))
Py4JError: An error occurred while calling o33.fqn. Trace:
py4j.Py4JException: Method fqn([]) does not exist
```

The reason is that the `TimePanel` object is a java object, and `IsSmvDataSet` method of java object does return some other java object instead of a python None, so `if obj.IsSmvDataSet` is valid. Should change the condition to `if obj.IsSmvDataSet == True`.

**Comment by laneb** [comment]
Duplicated by #1069, which is already fixed. Closing.
