### ISSUE TITLE
restore smvExportCsv functionality

### ISSUE THREAD

**Issue by kmannislands** [TresAmigosSD/SMV#1109]
It seems we've regressed on the shell command `smvExportCSV()`. It can't be called anymore from the `smv-pyshell` on master:

```Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 1.5.2+hotdeploy
      /_/

Using Python version 2.7.13 (default, Oct  4 2017 13:52:09)
SparkContext available as sc, HiveContext available as sqlContext.
SMV starting Py4j callback server on port 41271
>>> smvExportCsv
<function smvExportCsv at 0x108504230>
>>> smvExportCsv('app.stage.fileName.mod')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: smvExportCsv() takes exactly 2 arguments (1 given)
>>> smvExportCsv('app.stage.fileName.mod', 'path.csv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kieran/work/SMV/src/main/python/smv/smvshell.py", line 96, in smvExportCsv
    _jvmShellCmd().smvExportCsv(name, path)
  File "/Users/kieran/work/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/Users/kieran/work/spark/python/pyspark/sql/utils.py", line 36, in deco
    return f(*a, **kw)
  File "/Users/kieran/work/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 304, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling z:org.tresamigos.smv.shell.ShellCmd.smvExportCsv. Trace:
py4j.Py4JException: Method smvExportCsv([class java.lang.String, class java.lang.String]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:333)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:358)
	at py4j.Gateway.invoke(Gateway.java:254)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by AntonioRecaldeRusso** [comment]
The problem seems to the be that py4j does not recognize optional function arguments. I tested other functions exposed to the shell such as `exportToHive`, and they also do not work from the shell.
