### ISSUE TITLE
Support pyspark ml model in SmvModel

### ISSUE THREAD

**Issue by sarahnguvt** [TresAmigosSD/SMV#1309]
Since we will gradually move to spark 2.0+ and the `pyspark.ml` packages have also been improved a lot, I think it is better to also allow users to directly apply pyspark ml models in `SmvModel` (currently only native python model seems ok).

For example I created a `SmvModel` as below (with `SMV branch 2` and `spark 2.3`):
```python
from pyspark.ml.clustering import KMeans

class TestSPTrain(SmvModel):

    def requiresDS(self):
        return [inputset.CustomerAllFeatureTreat]

    def run(self, i):
        df = i[inputset.CustomerAllFeatureTreat]
        feature_list = ["cmcnt_seg_tvl_p1y", "cmcnt_lh_seg_tvl_p1y", "cmsum_rev_tvl_p1y", "cmint_age_now"]
        vecAssembler = VectorAssembler(inputCols=feature_list, outputCol="features")
        df_featvec = vecAssembler.transform(df)
        kmeans = KMeans(k=3, seed=1)
        model = kmeans.fit(df_featvec)

        return model
```

And will got below error when trying to execute:
```
>>> b=df("TestSPTrain")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xingyuwu/Software/SMV-use/src/main/python/smv/smvshell.py", line 41, in df
    return SmvApp.getInstance().runModuleByName(name, forceRun, version, runConfig, quickRun)[0]
  File "/Users/xingyuwu/Software/SMV-use/src/main/python/smv/smvapp.py", line 160, in func_wrapper
    raise e
py4j.protocol.Py4JJavaError: An error occurred while calling o33.runModuleByName.
: org.tresamigos.smv.SmvRuntimeException: There was an error executing Python code
	at org.tresamigos.smv.python.InterfacesWithPy4J$class.getPy4JResult(Py4JInterface.scala:28)
	at org.tresamigos.smv.SmvExtModulePython.getPy4JResult(SmvDataSet.scala:1197)
	at org.tresamigos.smv.SmvExtModulePython.doRun(SmvDataSet.scala:1219)
	at org.tresamigos.smv.SmvDataSet$$anonfun$computeDataFrame$1.apply(SmvDataSet.scala:603)
	at org.tresamigos.smv.SmvDataSet$$anonfun$computeDataFrame$1.apply(SmvDataSet.scala:597)
	at org.tresamigos.smv.SmvLock$.withLock(SmvLock.scala:70)
	at org.tresamigos.smv.SmvDataSet.computeDataFrame(SmvDataSet.scala:594)
	at org.tresamigos.smv.SmvDataSet.rdd(SmvDataSet.scala:250)
	at org.tresamigos.smv.SmvApp.runDS(SmvApp.scala:382)
	at org.tresamigos.smv.SmvApp.runModuleByName(SmvApp.scala:420)
	at org.tresamigos.smv.python.SmvPyClient.runModuleByName(SmvPythonProxy.scala:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.tresamigos.smv.python.SmvPythonException: The following error occurred whiling calling back to Python code
Traceback (most recent call last):
  File "/Users/xingyuwu/Software/SMV-use/src/main/python/smv/py4j_interface.py", line 35, in interface_method
    result = impl_method(*args)
  File "/Users/xingyuwu/Software/SMV-use/src/main/python/smv/smvdataset.py", line 573, in doRun
    result = self.result2df(self.smvApp, res_obj)
  File "/Users/xingyuwu/Software/SMV-use/src/main/python/smv/smvdataset.py", line 538, in result2df
    pickled_res = pickle_lib.dumps(res_obj, -1)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

**Comment by laneb** [comment]
The issue is that we serialize models with pickle and the model returned by pyspark isn't picklable. Objects can be made picklable by overriding `__getstate__`, so we may be able to make models picklable, but I'm not sure what the API for that would look like.

**Comment by laneb** [comment]
@AliTajeldin Priority?

**Comment by AliTajeldin** [comment]
@laneb will need this for Eddie 180 but less than the branch per task for now.
