### ISSUE TITLE
Compile failed with JAVA7

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#271]
On JAVA7

java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)

Compile error:
...
*** RUN ABORTED ***
  java.lang.UnsupportedClassVersionError: org/eclipse/jetty/server/handler/AbstractHandler : Unsupported major.minor version 52.0
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  ...

**Comment by AliTajeldin** [comment]
This was due to use of Jetty V9 which required Java 8.  Downgraded Jetty to V8 and all is working now.
