### ISSUE TITLE
discoverSchema should handle odd number of quotation marks (no as quotechar)

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#300]
when not used as quotechar, quotation marks sometime exist in data as cell content. when total number of quotation marks are odd, discoverSchema will fail. see below error messages in this case:

java.io.IOException: Un-terminated quoted field at end of CSV line
	at org.tresamigos.smv.CSVParser.parseLine(CSVParser.java:270)
	at org.tresamigos.smv.CSVParser.parseLine(CSVParser.java:180)
	at org.tresamigos.smv.SchemaDiscoveryHelper$$anonfun$discoverSchema$3.apply(SchemaDiscoveryHelper.scala:169)
	at org.tresamigos.smv.SchemaDiscoveryHelper$$anonfun$discoverSchema$3.apply(SchemaDiscoveryHelper.scala:168)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at org.tresamigos.smv.SchemaDiscoveryHelper.discoverSchema(SchemaDiscoveryHelper.scala:168)
	at org.tresamigos.smv.SchemaDiscoveryHelper.discoverSchemaFromFile(SchemaDiscoveryHelper.scala:200)

**Comment by AliTajeldin** [comment]
This is due to parseLine call raising an exception and SchemaDiscoveryHelper not catching the exception.  Need to do two things:
1. catch the exception from the line parser and ignore that line.
2. ensure that at least one line was parsed properly (otherwise, it means wrong CSV attributes were passed in)

**Comment by AliTajeldin** [comment]
Fixed
