### ISSUE TITLE
Classloader can't load anonymous functions within a module

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#310]
I have an anonymous function defined as 

``` scala
val mapfuc = (i: Integer) => ....
```

in a module. That module then can't be dynamically loaded. The error message is the following

```
Caused by: java.lang.ClassNotFoundException: com.omnicis.gsonar.etl.sharaw.PxRawFilter$$anonfun$5
```

**Comment by AliTajeldin** [comment]
Was finally able to reproduce this and capture the output.  Not sure if this is able to be reproduce consistently but here is what I did to get to fail:
1. rebuild smv and sample app from scratch.
2. clean the output directory.
3. run smv-shell.
4. dynamic load a module.
5. repeat previous step a few times.  It should always reload but not rerun (uses the cached data).
6. DO NOT exit the shell. In another window, edit the module.  Modify both the enclosing smv module and the anonymous function.
7. recompile the sample app.
8. reload the same module in the shell.
The above produced the following stack trace:
```
scala> val d = ddf("com.mycompany.myapp.stage1.EmploymentByState")
CL: loadClass: <root>.package
CL: loadClass: <root>.com
CL: loadClass: com
CL: findClass: com
CL: loadClass: com.package
CL: findClass: com.package
CL: loadClass: com.mycompany
CL: findClass: com.mycompany
CL: loadClass: com.mycompany.package
CL: findClass: com.mycompany.package
CL: loadClass: com.mycompany.myapp
CL: findClass: com.mycompany.myapp
CL: loadClass: com.mycompany.myapp.package
CL: findClass: com.mycompany.myapp.package
CL: loadClass: com.mycompany.myapp.stage1
CL: findClass: com.mycompany.myapp.stage1
CL: loadClass: com.mycompany.myapp.stage1.package
CL: findClass: com.mycompany.myapp.stage1.package
CL: loadClass: com.mycompany.myapp.stage1.EmploymentByState
CL: findClass: com.mycompany.myapp.stage1.EmploymentByState
CL: loadClass: java.lang.Object
CL: loadClass: scala.reflect.ScalaSignature
CL: loadClass: com.mycompany.myapp.stage1.EmploymentByState$
CL: findClass: com.mycompany.myapp.stage1.EmploymentByState$
CL: loadClass: org.tresamigos.smv.SmvOutput
CL: loadClass: org.tresamigos.smv.SmvModule
CL: loadClass: scala.Function1
CL: loadClass: scala.collection.Seq
CL: loadClass: com.mycompany.myapp.stage1.EmploymentByState$$anonfun$1
CL: findClass: com.mycompany.myapp.stage1.EmploymentByState$$anonfun$1
CL: loadClass: scala.Serializable
CL: loadClass: scala.runtime.AbstractFunction1
CL: loadClass: scala.collection.Seq$
CL: loadClass: scala.Predef$
CL: loadClass: com.mycompany.myapp.stage1.input.employment$
CL: findClass: com.mycompany.myapp.stage1.input.employment$
CL: loadClass: org.tresamigos.smv.SmvCsvFile
CL: loadClass: org.tresamigos.smv.SmvCsvFile$
java.io.IOException: Class not found
	at com.esotericsoftware.reflectasm.shaded.org.objectweb.asm.ClassReader.a(Unknown Source)
	at com.esotericsoftware.reflectasm.shaded.org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:40)
	at org.apache.spark.util.ClosureCleaner$.getInnerClosureClasses(ClosureCleaner.scala:81)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:187)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2032)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1849)
	at org.tresamigos.smv.DropRDDFunctions.drop(DropRDDFunctions.scala:48)
	at org.tresamigos.smv.CsvAttributes$.dropHeader(CsvAttributes.scala:37)
	at org.tresamigos.smv.FileIOHandler.csvFileWithSchema(FileIOHandler.scala:51)
	at org.tresamigos.smv.SmvCsvFile.doRun(SmvDataSet.scala:360)
	at org.tresamigos.smv.SmvDataSet.computeRDD(SmvDataSet.scala:205)
	at org.tresamigos.smv.SmvDataSet.rdd(SmvDataSet.scala:113)
	at org.tresamigos.smv.SmvApp.resolveRDD(SmvApp.scala:99)
	at org.tresamigos.smv.SmvModule$$anonfun$doRun$1.apply(SmvDataSet.scala:452)
	at org.tresamigos.smv.SmvModule$$anonfun$doRun$1.apply(SmvDataSet.scala:452)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.tresamigos.smv.SmvModule.doRun(SmvDataSet.scala:452)
	at org.tresamigos.smv.SmvDataSet$$anonfun$computeRDD$1.applyOrElse(SmvDataSet.scala:210)
	at org.tresamigos.smv.SmvDataSet$$anonfun$computeRDD$1.applyOrElse(SmvDataSet.scala:209)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
	at scala.util.Failure.recoverWith(Try.scala:172)
	at org.tresamigos.smv.SmvDataSet.computeRDD(SmvDataSet.scala:209)
	at org.tresamigos.smv.SmvDataSet.rdd(SmvDataSet.scala:113)
	at org.tresamigos.smv.SmvApp.resolveRDD(SmvApp.scala:99)
	at org.tresamigos.smv.SmvApp.dynamicResolveRDD(SmvApp.scala:123)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$i$.ddf(<console>:51)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:39)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:44)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:46)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:48)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:50)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:52)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:54)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:56)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:58)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:60)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:62)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:64)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:66)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:68)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:70)
	at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:72)
	at $iwC$$iwC$$iwC$$iwC.<init>(<console>:74)
	at $iwC$$iwC$$iwC.<init>(<console>:76)
	at $iwC$$iwC.<init>(<console>:78)
	at $iwC.<init>(<console>:80)
	at <init>(<console>:82)
	at .<init>(<console>:86)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
...
```

Note: restarting the shell will work fine.  Something is being cached in Spark that is failing during closure cleanup.  Need to investigate further.

**Comment by AliTajeldin** [comment]
It appears that the anonymous function was a red herring.  The issue has nothing to do with anonymous functions. The above can be reproduced even if we create an SMV module without an anonymous function.  The critical step seems to be step 7.  If we rebuild the app using "maven clean install" then it works fine.  If we just rebuilt using "maven install" then it fails as above.  The odd part is if we just do the "clean" step the first time then subsequent "maven install" work fine.   Now that it is easy to reproduce, we can start looking at the spark code to figure out what it is trying to do.

**Comment by Kai-Chen** [comment]
See patch for Spark 1.5.2 [here](https://github.com/Kai-Chen/spark/commit/ed413dd5b1d64cd7624fb28fb385a1150933548b)
