### ISSUE TITLE
SBT publish-local / compile error in the latest Docker image

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#331]
I am pretty unfamiliar with SBT, so I'm hoping this is an easy ticket to close. 

I am getting errors related to unresovled dependeices on `org.tresamigos:smv_2.10:1.5-SNAPSHOT`. 

Can someone offer me any suggestions?

**Steps to reproduce:**
1. `docker run -it --rm jacobdr/smv:4bd6ce6 bash` (`4bd6ce6` is the latest commit I built image on)
2. `smv-init test com.testproject`
3. `cd test`
4. `sbt publish-local`

```
user@smv:/projects/test$ sbt publish-local
Getting org.scala-sbt sbt 0.13.11 ...

[[[ .... TRUNCATED ... ]]]

[info] 	[SUCCESSFUL ] javax.inject#javax.inject;1!javax.inject.jar (602ms)
[info] Done updating.
[info] Set current project to testproject (in build file:/projects/test/)
[info] Updating {file:/projects/test/}test...
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[info] Packaging /projects/test/target/scala-2.10/testproject_2.10-1.0-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] Resolving org.tresamigos#smv_2.10;1.5-SNAPSHOT ...
[warn] 	module not found: org.tresamigos#smv_2.10;1.5-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/smv/.ivy2/local/org.tresamigos/smv_2.10/1.5-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/tresamigos/smv_2.10/1.5-SNAPSHOT/smv_2.10-1.5-SNAPSHOT.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...

[[[ .... TRUNCATED ... ]]]

[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.4/scala-compiler-2.10.4.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.10.4!scala-compiler.jar (5421ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/jline/2.10.4/jline-2.10.4.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#jline;2.10.4!jline.jar (1404ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.tresamigos#smv_2.10;1.5-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.tresamigos:smv_2.10:1.5-SNAPSHOT (/projects/test/build.sbt#L13-19)
[warn] 		  +- com:testproject_2.10:1.0-SNAPSHOT
[info] Wrote /projects/test/target/scala-2.10/testproject_2.10-1.0-SNAPSHOT.pom
sbt.ResolveException: unresolved dependency: org.tresamigos#smv_2.10;1.5-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.tresamigos#smv_2.10;1.5-SNAPSHOT: not found
[error] Total time: 405 s, completed Jul 22, 2016 5:55:04 PM
```

**Comment by Kai-Chen** [comment]
We don't have a public repository for SMV yet.  So typically developers working on specific projects that rely on SMV need to checkout and build the SNAPSHOT jar.  And you need to use the same tool (mvn, sbt) to build both SMV and the dependent project.

I think there's a way to tell sbt to use maven's local repository; I will check that in soon, so transitioning from maven to sbt will be easier (at least the internet-downloading part should be skipped).

cc @laneb

**Comment by jacobdr** [comment]
Resolved with recent commits. See #342
