### ISSUE TITLE
runModule and runDynamicModule call on smvPyModule in smv-pyshell do not show correct error track

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#408]
If there are any issues in the smvPyModule (either syntax error or unresolvable column type of errors), when try to resolve using either `runModule` or `runDynamicModule`, the error message is very generic, which has zero help for identifying the problem. 

Because of this, we have to keep the `run_python_module` method for now, until this issue get resolved on `runModule` and `runDynamicModule`.

**Comment by ninjapapa** [comment]
Here is the error message when I intentionally introduced a syntax error in a smvPyModule,
```
>>> running module com.mycompany.MyApp.stage1.employment.PythonEmploymentByState
running module com.mycompany.MyApp.stage1.inputdata.PythonEmployment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bzhang/Tresamigos/SMV/python/smvshell.py", line 20, in <lambda>
    ddf = lambda fqn: SmvApp.runDynamicModule(fqn)
  File "/Users/bzhang/Tresamigos/SMV/python/smv.py", line 194, in runDynamicModule
    return DataFrame(self.app.runDynamicModule(fqn, self.repo), self.sqlContext)
  File "/Users/bzhang/spark-1.5.2/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/Users/bzhang/spark-1.5.2/python/pyspark/sql/utils.py", line 36, in deco
    return f(*a, **kw)
  File "/Users/bzhang/spark-1.5.2/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o25.runDynamicModule.
: py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: x
        at py4j.Protocol.getReturnValue(Protocol.java:417)
        at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:113)
        at com.sun.proxy.$Proxy25.getDataFrame(Unknown Source)
        at org.tresamigos.smv.SmvApp.runModule(SmvApp.scala:359)
        at org.tresamigos.smv.SmvApp.runDynamicModule(SmvApp.scala:405)
        at org.tresamigos.smv.python.SmvPythonApp.runDynamicModule(SmvPythonProxy.scala:175)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:207)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ninjapapa** [comment]
As a temporary solution, rollback to `run_python_module` for the `pdf` pyshell command.

**Comment by Kai-Chen** [comment]
If the python code doesn't compile, we will still have an error-reporting problem.  This is because the error message is 'Cannot find module ...` because the error happens at module import time.  We'd need to manually compile the code and check that it's okay.  That'd take some time.  So I will save that for later.

Hope this check-in is enough for now.

**Comment by ninjapapa** [comment]
Can we add a pyshell command to force a compile on project dirs? If so at least when we run into 'cannot find module' error, we can run that command, which should should compile time errors.

**Comment by Kai-Chen** [comment]
There's still a problem with the previous fix: if the first `runDynamicModule` fails in `run()`, the module is still loaded, but not the resulting dataframe.  Need to force reload the python module.

**Comment by Kai-Chen** [comment]
The above commit should fix everything now.

I added another ticket #411 for enhancement on the Python side of SMV.

Reload-on-change is also possible for Scala.

**Comment by ninjapapa** [comment]
done.
