### ISSUE TITLE
smv-pyrun fails with exception when running a module.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#441]
Failed running the sample app using latest SMV on master.
```
$ smv-pyrun -m com.c.p.stage1.employment.PythonEmploymentByState
START RUN ==============================
Wed Nov 30 19:51:15 PST 2016
Spark Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/bin/java -cp target/p-1.0-SNAPSHOT-jar-with-dependencies.jar:/Users/alitajeldin/Pkgs/spark/conf/:/Users/alitajeldin/Pkgs/spark/assembly/target/scala-2.10/spark-assembly-1.5.2-hadoop2.6.0.jar:/Users/alitajeldin/Pkgs/spark/lib_managed/jars/datanucleus-api-jdo-3.2.6.jar:/Users/alitajeldin/Pkgs/spark/lib_managed/jars/datanucleus-core-3.2.10.jar:/Users/alitajeldin/Pkgs/spark/lib_managed/jars/datanucleus-rdbms-3.2.9.jar -Xms2G -Xmx2G org.apache.spark.deploy.SparkSubmit --master local[*] --conf spark.driver.memory=2G --conf spark.driver.extraClassPath=target/p-1.0-SNAPSHOT-jar-with-dependencies.jar --executor-memory 6G --jars target/p-1.0-SNAPSHOT-jar-with-dependencies.jar /Users/alitajeldin/AtomProjects/SMV/tools/../python/smvapp.py -m com.c.p.stage1.employment.PythonEmploymentByState
========================================
16/11/30 19:51:16 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/11/30 19:51:18 WARN MetricsSystem: Using default name DAGScheduler for source because spark.app.id is not set.
starting callback server on port 25334
----------------------------------------
will run/publish the following modules:
   com.c.p.stage1.employment.PythonEmploymentByState
----------------------------------------
running module com.c.p.stage1.employment.PythonEmploymentByState
running module com.c.p.stage1.inputdata.PythonEmployment
Traceback (most recent call last):
  File "/Users/alitajeldin/AtomProjects/SMV/tools/../python/smvapp.py", line 47, in <module>
    smvPy.runModule(name)
  File "/Users/alitajeldin/AtomProjects/SMV/python/smv.py", line 293, in runModule
    jdf = self.j_smvPyClient.runModule(fqn, self.repo)
  File "/Users/alitajeldin/Pkgs/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/Users/alitajeldin/Pkgs/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
  File "/Users/alitajeldin/Pkgs/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o23.runModule.
: py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: x
	at py4j.Protocol.getReturnValue(Protocol.java:417)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:113)
```

**Comment by Kai-Chen** [comment]
Works for me :) I would guess that you might have skipped the `smv-init` step.  The example project needs to be regenerated because of the naming refactor.  Also run `sbt publish-local` from SMV and doing another `sbt assembly` from the example project would usually solve the issue.  Let me know if there's still a problem after these steps

**Comment by Kai-Chen** [comment]
Also, to run a scala module using `smv-pyrun`, or a python module that uses a scala module as a dependency or link, you'd need to manually *activate* the new code by swapping the commented-out and the active section in `SmvModule.doRun` in `SmvDataSet.scala` (lines 439-440 right now).  The old code was left as default to make sure existing apps won't break.
