### ISSUE TITLE
Solve the conflict between smv-server and smv-jupyter

### ISSUE THREAD

**Issue by guangningyu** [TresAmigosSD/SMV#457]
It seems that there's a conflict between `smv-server` and `smv-jupyter`, which create multiple instances of Spark-Shell and hold derby DB.

The entrypoint is like:
```
smv-jupyter &
smv-server
```

The error is:
```
Caused by: java.sql.SQLException: Failed to start database 'metastore_db' with class loader org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1@6b6e7285, see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 89 more
Caused by: java.sql.SQLException: Another instance of Derby may have already booted the database /projects/MyApp/metastore_db.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	... 86 more
```

Here is a discussion about this issue:
http://stackoverflow.com/questions/34465516/caused-by-error-xsdb6-another-instance-of-derby-may-have-already-booted-the-da

**Comment by guangningyu** [comment]
Separating smv-server and smv-jupyter in docker entrypoint does not solve the problem.
The reason why the error was gone is that each container creates a sample app project and started the server in each own project. The error will be thrown again if these two containers mount the same SMV project.

**Comment by guangningyu** [comment]
Since both Jupyter notebook and SMV server needs to access the Derby database, we may consider using Derby Network Server.

**Comment by guangningyu** [comment]
According to this [thread](https://github.com/spark-jobserver/spark-jobserver/issues/519), we can use an in-memory Derby instance for Hive metastore instead of a local Derby instance.
In this way, we can avoid the conflict of multiple HiveContext.
