### ISSUE TITLE
running smv-pyshell after smv-init causes a stack dump

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#494]
Just running these two steps,
```bash
$ smv-init -s foo a.b.c
$ smv-pyshell
```
Causes the following error:
```
$ smv-pyshell
APP_JAR = /Users/alitajeldin/AtomProjects/SMV/tools/../target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar
Spark Command: python2.7
========================================
Python 2.7.8 (default, Aug  3 2016, 12:04:37) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Spark Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/bin/java -cp /Users/alitajeldin/AtomProjects/SMV/tools/../target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar:/Users/alitajeldin/Pkgs/spark/conf/:/Users/alitajeldin/Pkgs/spark/assembly/target/scala-2.10/spark-assembly-1.5.2-hadoop2.6.0.jar:/Users/alitajeldin/Pkgs/spark/lib_managed/jars/datanucleus-api-jdo-3.2.6.jar:/Users/alitajeldin/Pkgs/spark/lib_managed/jars/datanucleus-core-3.2.10.jar:/Users/alitajeldin/Pkgs/spark/lib_managed/jars/datanucleus-rdbms-3.2.9.jar -Xms1g -Xmx1g org.apache.spark.deploy.SparkSubmit --conf spark.driver.extraClassPath=/Users/alitajeldin/AtomProjects/SMV/tools/../target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar --name PySparkShell --jars /Users/alitajeldin/AtomProjects/SMV/tools/../target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar pyspark-shell
========================================
17/02/20 18:55:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/02/20 18:55:47 WARN MetricsSystem: Using default name DAGScheduler for source because spark.app.id is not set.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 1.5.2
      /_/

Using Python version 2.7.8 (default, Aug  3 2016 12:04:37)
SparkContext available as sc, HiveContext available as sqlContext.
SmvApp: Failed to parse the trailing argument list: ''
Traceback (most recent call last):
  File "/Users/alitajeldin/Pkgs/spark/python/pyspark/shell.py", line 79, in <module>
    execfile(_pythonstartup)
  File "smv_pyshell_init.py", line 51, in <module>
    app = smvPy.init(['-m', 'None', '--cbs-port', str(callback_server_port)] + smv_args, sc, sqlContext)
  File "/Users/alitajeldin/AtomProjects/SMV/python/smv.py", line 175, in init
    self.j_smvPyClient = self.create_smv_pyclient(arglist)
  File "/Users/alitajeldin/AtomProjects/SMV/python/smv.py", line 217, in create_smv_pyclient
    return self._jvm.org.tresamigos.smv.python.SmvPyClientFactory.init(java_args, self.sqlContext._ssql_ctx)
  File "/Users/alitajeldin/Pkgs/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/Users/alitajeldin/Pkgs/spark/python/pyspark/sql/utils.py", line 36, in deco
    return f(*a, **kw)
  File "/Users/alitajeldin/Pkgs/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.tresamigos.smv.python.SmvPyClientFactory.init.
: org.tresamigos.smv.SmvRuntimeException: Failed to parse the trailing argument list: ''
	at org.tresamigos.smv.CmdLineArgsConf$$anonfun$22.apply(SmvConfig.scala:102)
	at org.tresamigos.smv.CmdLineArgsConf$$anonfun$22.apply(SmvConfig.scala:100)
	at org.rogach.scallop.ScallopConf.onError(ScallopConf.scala:331)
	at org.rogach.scallop.ScallopConf.verify(ScallopConf.scala:272)
	at org.rogach.scallop.ScallopConf.afterInit(ScallopConf.scala:504)
	at org.rogach.scallop.AfterInit$class.delayedInit(AfterInit.scala:14)
	at org.rogach.scallop.ScallopConf.delayedInit(ScallopConf.scala:26)
	at org.tresamigos.smv.CmdLineArgsConf.<init>(SmvConfig.scala:28)
	at org.tresamigos.smv.SmvConfig.<init>(SmvConfig.scala:127)
	at org.tresamigos.smv.SmvApp.<init>(SmvApp.scala:35)
	at org.tresamigos.smv.SmvApp$.init(SmvApp.scala:635)
	at org.tresamigos.smv.python.SmvPyClientFactory$.init(SmvPythonProxy.scala:229)
	at org.tresamigos.smv.python.SmvPyClientFactory.init(SmvPythonProxy.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by laneb** [comment]
When no args were passed to smv-pyshell, an empty string was being added to the SmvApp argument array. Fixed.
