### ISSUE TITLE
Mixed Scala/Python projects don't work with smv-run

### ISSUE THREAD

**Issue by hubertp-lshift** [TresAmigosSD/SMV#595]
```
smv-init -t SomeApp
cd SomeApp
sbt assemble
smv-pyrun --run-app
// ... ok
smv-run --run-app
```
will give you this
```
ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
Exception in thread "main" org.tresamigos.smv.SmvRuntimeException: SmvDataSet mod:org.tresamigos.smvtest.test5.modules.M1 not found
	at org.tresamigos.smv.DataSetResolver.org$tresamigos$smv$DataSetResolver$$findDataSetInRepo(DataSetResolver.scala:108)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1$$anonfun$apply$1.apply(DataSetResolver.scala:47)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1$$anonfun$apply$1.apply(DataSetResolver.scala:41)
	at scala.Option.getOrElse(Option.scala:121)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:41)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:40)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.tresamigos.smv.DataSetResolver.loadDataSet(DataSetResolver.scala:39)
	at org.tresamigos.smv.SmvExtModule.resolve(SmvDataSet.scala:608)
	at org.tresamigos.smv.DataSetResolver$$anonfun$resolveDataSet$1.apply(DataSetResolver.scala:70)
	at org.tresamigos.smv.DataSetResolver$$anonfun$resolveDataSet$1.apply(DataSetResolver.scala:68)
	at scala.Option.getOrElse(Option.scala:121)
	at org.tresamigos.smv.DataSetResolver.resolveDataSet(DataSetResolver.scala:68)
	at org.tresamigos.smv.SmvDataSet$$anonfun$resolve$1.apply(SmvDataSet.scala:73)
	at org.tresamigos.smv.SmvDataSet$$anonfun$resolve$1.apply(SmvDataSet.scala:73)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.tresamigos.smv.SmvDataSet.resolve(SmvDataSet.scala:73)
	at org.tresamigos.smv.DataSetResolver$$anonfun$resolveDataSet$1.apply(DataSetResolver.scala:70)
	at org.tresamigos.smv.DataSetResolver$$anonfun$resolveDataSet$1.apply(DataSetResolver.scala:68)
	at scala.Option.getOrElse(Option.scala:121)
	at org.tresamigos.smv.DataSetResolver.resolveDataSet(DataSetResolver.scala:68)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1$$anonfun$apply$1.apply(DataSetResolver.scala:49)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1$$anonfun$apply$1.apply(DataSetResolver.scala:41)
	at scala.Option.getOrElse(Option.scala:121)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:41)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:40)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.tresamigos.smv.DataSetResolver.loadDataSet(DataSetResolver.scala:39)
	at org.tresamigos.smv.DataSetMgr.load(DataSetMgr.scala:40)
	at org.tresamigos.smv.DataSetMgr.allDataSets(DataSetMgr.scala:62)
	at org.tresamigos.smv.DataSetMgr.allOutputModules(DataSetMgr.scala:65)
	at org.tresamigos.smv.SmvApp.modulesToRun$lzycompute(SmvApp.scala:232)
	at org.tresamigos.smv.SmvApp.modulesToRun(SmvApp.scala:224)
	at org.tresamigos.smv.SmvApp.run(SmvApp.scala:241)
	at org.tresamigos.smv.SmvApp$.main(SmvApp.scala:282)
	at org.tresamigos.smv.SmvApp.main(SmvApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Maybe I miss something but from the documentation (and some commits) it looks to me like the dependencies should be correctly resolved irrespective of whether we start it through pyspark or spark.

**Comment by ninjapapa** [comment]
By design it should be. However, we currently more focus on the python side. Since in the future we expect more users will use pure Python, or will build Python modules on some legacy Scala projects, we are majorly testing on that type of scenarios. We are actually planning to deprecate smv-run and rename smv-pyrun as smv-run. 

Two ways to address this issue:

* Fix smv-run 
* Remove smv-run and update document 

I will definitely prefer the 2nd approach. If you think we need to keep smv-run, please share your use case which smv-pyrun can't be used.

**Comment by laneb** [comment]
To be more specific, SMV won't discover any Python modules when an application is run with `smv-run`. I agree with @ninjapapa that option 2 is better.

**Comment by hubertp-lshift** [comment]
I imagine that the scala `runner` (or whatever you call it) would have to be able to start the gateway so that it can call python code in some known location. AFAIK py4j is capable of doing so. so it shouldn't be a big problem. Instead of removing completely `smv-run` I would just document it for now that the framework doesn't support mixed projects if the App is started in Scala. It would be a pity to drop it completely if I would like to stay only in the Scala world.

**Comment by laneb** [comment]
What would be the difference from the user's perspective between `smv-pyrun` and `smv-run` as you've described it? Just that `smv-run` doesn't require Python to be installed?

**Comment by hubertp-lshift** [comment]
I thought it requires at least some Python boilerplate code? If not, then yeah, probably not needed. FYI I had a quick look into py4j, just out of my personal curiosity on how it works, and I could play around with adding support for this feature.

**Comment by laneb** [comment]
No boilerplate required. For an example, you can generate a (very trivial) pure Scala project with the following
```
smv-init -t test
cd test
rm -rf src/main/python
rm -rf src/main/scala/org/tresamigos/smvtest/test*
rm -rf src/main/scala/org/tresamigos/smvtest/stage2
head -24 src/main/scala/org/tresamigos/smvtest/stage1/EmploymentByState.scala > src/main/scala/org/tresamigos/smvtest/stage1/EmploymentByState.scala2
mv src/main/scala/org/tresamigos/smvtest/stage1/EmploymentByState.scala2 src/main/scala/org/tresamigos/smvtest/stage1/EmploymentByState.scala
```
and you will be able to assemble run it with `smv-pyrun`. The reason why you were unable to run the normal test app is because it has Scala modules that depend on Python modules.

**Comment by hubertp-lshift** [comment]
Yes, I did found out that Python `DataSetRepo` is not taken into account when running through `smv-run`. But I was expecting it to work, since `smv-pyrun` can work with both, Scala and Python, `DataSetRepo`s.
Anyway, in the end, I agree that renaming is probably the least annoying change to make, provided that there are no perf implications.

**Comment by AliTajeldin** [comment]
We should create an smv-run that just delegates to smv-pyrun and print a deprecation message and remove all references to `smv-run` from the docs.

**Comment by AliTajeldin** [comment]
An alternative as pointed out by @laneb is to make `smv-pyrun` be `smv-run` and add make `smv-pyrun` a redirect with the message.

**Comment by jacobdr** [comment]
I think the second is cleaner. It makes much more sense when there actually is a mixed Scala-Python codebase... let alone a Scala only codebase, which I'm not so quick to write off.

**Comment by laneb** [comment]
Deprecating smv-pyrun is covered by #888.
