### ISSUE TITLE
smvConcatHist non-function

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#681]
see below error:
```
Py4JError                                 Traceback (most recent call last)
<ipython-input-11-739cd70c0a58> in <module>()
----> 1 phys.smvConcatHist(["mdm_prim_spcl_cde", "mdm_sec_spcl_cde"])

/home/cchen/SMV/src/main/python/smv/helpers.pyc in method(self, *args, **kwargs)
    207 def _getUnboundMethod(helperCls, methodName):
    208     def method(self, *args, **kwargs):
--> 209         return getattr(helperCls(self), methodName)(*args, **kwargs)
    210     method.__name__ = methodName
    211     return method

/home/cchen/SMV/src/main/python/smv/helpers.pyc in smvConcatHist(self, *cols)
    837                 (None)
    838         """
--> 839         self._println(self._smvConcatHist(*cols))
    840 
    841     def _smvFreqHist(self, *cols):

/home/cchen/SMV/src/main/python/smv/helpers.pyc in _smvConcatHist(self, *cols)
    823 
    824     def _smvConcatHist(self, *cols):
--> 825         return self._jPythonHelper.smvConcatHist(self._jdf, smv_copy_array(self._sc, *cols))
    826 
    827     def smvConcatHist(self, *cols):

/usr/local/spark/current/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    536         answer = self.gateway_client.send_command(command)
    537         return_value = get_return_value(answer, self.gateway_client,
--> 538                 self.target_id, self.name)
    539 
    540         for temp_arg in temp_args:

/usr/local/spark/current/python/pyspark/sql/utils.py in deco(*a, **kw)
     34     def deco(*a, **kw):
     35         try:
---> 36             return f(*a, **kw)
     37         except py4j.protocol.Py4JJavaError as e:
     38             s = e.java_exception.toString()

/usr/local/spark/current/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    302                 raise Py4JError(
    303                     'An error occurred while calling {0}{1}{2}. Trace:\n{3}\n'.
--> 304                     format(target_id, '.', name, value))
    305         else:
    306             raise Py4JError(

Py4JError: An error occurred while calling z:org.tresamigos.smv.python.SmvPythonHelper.smvConcatHist. Trace:
py4j.Py4JException: Method smvConcatHist([class org.apache.spark.sql.DataFrame, class java.util.ArrayList]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:333)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:358)
	at py4j.Gateway.invoke(Gateway.java:254)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by laneb** [comment]
`smvConcatHist` has signature `smvConcatHist(self, *cols)`. Try `phys.smvConcatHist("mdm_prim_spcl_cde", "mdm_sec_spcl_cde")` instead of `phys.smvConcatHist(["mdm_prim_spcl_cde", "mdm_sec_spcl_cde"])`.

**Comment by XiaosenChen** [comment]
Close, correct user doc at 3c8f1f44c9c74a08c703e7c210895321f04bef8e
