### ISSUE TITLE
Scala tests fail when run with maven

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#753]
Running `mvn test` on master currently results in 3 failed tests. Note `sbt test` passes all tests.

**Comment by laneb** [comment]
```
SmvWhatModulesToRunTest:
- Test modules to run (non-output module) *** FAILED ***
  org.tresamigos.smv.SmvRuntimeException: Cannot find module with FQN [org.tresamigos.smv.smvAppTestPkg3.T]. Is the stage name specified in the config?
  at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:50)
  at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:46)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  at scala.collection.immutable.List.foreach(List.scala:318)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
  at scala.collection.AbstractTraversable.map(Traversable.scala:105)
  at org.tresamigos.smv.DataSetResolver.loadDataSet(DataSetResolver.scala:46)
  at org.tresamigos.smv.TX.load(Transaction.scala:33)
  at org.tresamigos.smv.TX.inferDS(Transaction.scala:58)
  ...
- Test modules to run (mods in stage) *** FAILED ***
  org.tresamigos.smv.SmvRuntimeException: Cannot find module with FQN [org.tresamigos.smv.smvAppTestPkg1.Y]. Is the stage name specified in the config?
  at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:50)
  at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:46)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  at scala.collection.immutable.List.foreach(List.scala:318)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
  at scala.collection.AbstractTraversable.map(Traversable.scala:105)
  at org.tresamigos.smv.DataSetResolver.loadDataSet(DataSetResolver.scala:46)
  at org.tresamigos.smv.TX.load(Transaction.scala:33)
  at org.tresamigos.smv.TX.dataSetsForStage(Transaction.scala:42)
  ...
- Test modules to run (mods in app) *** FAILED ***
  org.tresamigos.smv.SmvRuntimeException: Cannot find module with FQN [org.tresamigos.smv.smvAppTestPkg1.Y]. Is the stage name specified in the config?
  at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:50)
  at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:46)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  at scala.collection.immutable.List.foreach(List.scala:318)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
  at scala.collection.AbstractTraversable.map(Traversable.scala:105)
  at org.tresamigos.smv.DataSetResolver.loadDataSet(DataSetResolver.scala:46)
  at org.tresamigos.smv.TX.load(Transaction.scala:33)
  at org.tresamigos.smv.TX.allDataSets(Transaction.scala:45)
  ...
```

**Comment by laneb** [comment]
Could be related to #715. Per @AliTajeldin we will be dropping support for mvn soon anyway, but we should still try to understand what's happening here.

**Comment by laneb** [comment]
Because `SmvWhatModulesToRunTest` does not extend `SmvTestUtil`, it does not register a new singleton `SmvApp` when the test starts up. Each test in `SmvWhatModulesToRunTest` creates its own `SmvApp` using `SmvApp's` constructor, and does not register it as the singleton. Thus, when URN asks for the singleton `SmvApp` it gets the wrong one, which must have belonged to another test. Most likely, the reason for passing SBT and failing Maven is just the order of the tests - there are other tests using the same stages, so most likely we are by chance picking up one of those tests's `SmvApp`.
