### ISSUE TITLE
sbt pytest fails

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#822]
```
======================================================================
ERROR: test_SmvCsvFileWithUserSchema (testSmvFramework.SmvFrameworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bzhang/Tresamigos/SMV/src/test/python/testSmvFramework.py", line 58, in test_SmvCsvFileWithUserSchema
    df = self.df(fqn)
  File "/Users/bzhang/Tresamigos/SMV/src/main/python/test_support/smvbasetest.py", line 67, in df
    return cls.smvApp.runModule("mod:" + fqn)
  File "/Users/bzhang/Tresamigos/SMV/src/main/python/smv/smvapp.py", line 153, in runModule
    jdf = self.j_smvPyClient.runModule(urn, forceRun, self.scalaOption(version))
  File "/Users/bzhang/spark-1.5.2/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
    self.target_id, self.name)
  File "/Users/bzhang/spark-1.5.2/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
    return f(*a, **kw)
  File "/Users/bzhang/spark-1.5.2/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
    format(target_id, '.', name), value)
Py4JJavaError: An error occurred while calling o1576.runModule.
: py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: x
	at py4j.Protocol.getReturnValue(Protocol.java:417)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:113)
	at com.sun.proxy.$Proxy33.instanceValHash(Unknown Source)
	at org.tresamigos.smv.SmvExtModulePython.instanceValHash(SmvDataSet.scala:946)
	at org.tresamigos.smv.SmvDataSet.datasetHash(SmvDataSet.scala:122)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvDataSet.verHex(SmvDataSet.scala:210)
	at org.tresamigos.smv.SmvDataSet.versionedFqn(SmvDataSet.scala:211)
	at org.tresamigos.smv.SmvDataSet.rdd(SmvDataSet.scala:204)
	at org.tresamigos.smv.SmvApp.runDS(SmvApp.scala:299)
	at org.tresamigos.smv.SmvApp.runModule(SmvApp.scala:310)
	at org.tresamigos.smv.python.SmvPyClient.runModule(SmvPythonProxy.scala:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)


======================================================================
ERROR: test_SmvMultiCsvFilesWithUserSchema (testSmvFramework.SmvFrameworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bzhang/Tresamigos/SMV/src/test/python/testSmvFramework.py", line 68, in test_SmvMultiCsvFilesWithUserSchema
    df = self.df(fqn)
  File "/Users/bzhang/Tresamigos/SMV/src/main/python/test_support/smvbasetest.py", line 67, in df
    return cls.smvApp.runModule("mod:" + fqn)
  File "/Users/bzhang/Tresamigos/SMV/src/main/python/smv/smvapp.py", line 153, in runModule
    jdf = self.j_smvPyClient.runModule(urn, forceRun, self.scalaOption(version))
  File "/Users/bzhang/spark-1.5.2/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
    self.target_id, self.name)
  File "/Users/bzhang/spark-1.5.2/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
    return f(*a, **kw)
  File "/Users/bzhang/spark-1.5.2/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
    format(target_id, '.', name), value)
Py4JJavaError: An error occurred while calling o1576.runModule.
: py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: x
	at py4j.Protocol.getReturnValue(Protocol.java:417)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:113)
	at com.sun.proxy.$Proxy33.instanceValHash(Unknown Source)
	at org.tresamigos.smv.SmvExtModulePython.instanceValHash(SmvDataSet.scala:946)
	at org.tresamigos.smv.SmvDataSet.datasetHash(SmvDataSet.scala:122)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvDataSet.verHex(SmvDataSet.scala:210)
	at org.tresamigos.smv.SmvDataSet.versionedFqn(SmvDataSet.scala:211)
	at org.tresamigos.smv.SmvDataSet.rdd(SmvDataSet.scala:204)
	at org.tresamigos.smv.SmvApp.runDS(SmvApp.scala:299)
	at org.tresamigos.smv.SmvApp.runModule(SmvApp.scala:310)
	at org.tresamigos.smv.python.SmvPyClient.runModule(SmvPythonProxy.scala:234)
	at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)


----------------------------------------------------------------------
```

**Comment by laneb** [comment]
`sbt pytest` passes on master on my system. Any special instructions to replicate?

**Comment by laneb** [comment]
Notably I seem to be getting the same error when trying to run the python tests on [Travis](https://travis-ci.org/TresAmigosSD/SMV/builds/236117570?utm_source=email&utm_medium=notification). What version Python are you using?

**Comment by ninjapapa** [comment]
```
$ python --version
Python 2.7.13
```

**Comment by Khorkhe** [comment]
I am getting a different error for the python tests (19 of them, 2 shown):

```
======================================================================
ERROR: setUpClass (testSmvfuncs.SmvfuncsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/khorkhe/Desktop/twine/SMV/src/main/python/test_support/smvbasetest.py", line 42, in setUpClass
    cls.smvApp = SmvApp.createInstance(args, cls.sparkContext, cls.sqlContext)
  File "/Users/khorkhe/Desktop/twine/SMV/src/main/python/smv/smvapp.py", line 65, in createInstance
    cls._instance = cls(arglist, _sc, _sqlContext)
  File "/Users/khorkhe/Desktop/twine/SMV/src/main/python/smv/smvapp.py", line 87, in __init__
    self.j_smvPyClient = self.create_smv_pyclient(arglist)
  File "/Users/khorkhe/Desktop/twine/SMV/src/main/python/smv/smvapp.py", line 142, in create_smv_pyclient
    return self._jvm.org.tresamigos.smv.python.SmvPyClientFactory.init(java_args, self.sqlContext._ssql_ctx)
  File "/Users/khorkhe/Desktop/twine/spark-1.5.2-bin-hadoop2.6/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 726, in __getattr__
    raise Py4JError('Trying to call a package.')
Py4JError: Trying to call a package.

======================================================================
ERROR: setUpClass (testSmvGroupedData.GroupedDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/khorkhe/Desktop/twine/SMV/src/main/python/test_support/smvbasetest.py", line 42, in setUpClass
    cls.smvApp = SmvApp.createInstance(args, cls.sparkContext, cls.sqlContext)
  File "/Users/khorkhe/Desktop/twine/SMV/src/main/python/smv/smvapp.py", line 65, in createInstance
    cls._instance = cls(arglist, _sc, _sqlContext)
  File "/Users/khorkhe/Desktop/twine/SMV/src/main/python/smv/smvapp.py", line 87, in __init__
    self.j_smvPyClient = self.create_smv_pyclient(arglist)
  File "/Users/khorkhe/Desktop/twine/SMV/src/main/python/smv/smvapp.py", line 142, in create_smv_pyclient
    return self._jvm.org.tresamigos.smv.python.SmvPyClientFactory.init(java_args, self.sqlContext._ssql_ctx)
  File "/Users/khorkhe/Desktop/twine/spark-1.5.2-bin-hadoop2.6/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 726, in __getattr__
    raise Py4JError('Trying to call a package.')
Py4JError: Trying to call a package.

----------------------------------------------------------------------
Ran 0 tests in 6.795s

FAILED (errors=19)
('result is ', <unittest.runner.TextTestResult run=0 errors=19 failures=0>)
java.lang.IllegalStateException: pytest failed
	at $3e85ef813cc01ad77d16$$anonfun$$sbtdef$1.apply(/Users/khorkhe/Desktop/twine/SMV/build.sbt:43)
	at $3e85ef813cc01ad77d16$$anonfun$$sbtdef$1.apply(/Users/khorkhe/Desktop/twine/SMV/build.sbt:40)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:pytest) java.lang.IllegalStateException: pytest failed
[error] Total time: 130 s, completed May 30, 2017 11:19:02 AM
```

**Comment by Khorkhe** [comment]
this failure actually also occurs when attempting to run smv-pyrun / smv-pyshell shell commands.  This is happening since this morning

**Comment by laneb** [comment]
The tests are all passing on my system both on 2.7.10 (which I have been developing with and which @Khorkhe is using) and on 2.7.13, so this appears to be version independent.

**Comment by laneb** [comment]
Was able to replicate @ninjapapa's issue on both 2.7.10 and 2.7.13 after running `sbt clean`. I suspect @Khorkhe's issue is unrelated. May need to open a separate issue.

**Comment by laneb** [comment]
Source of @ninjapapa's problem is that the location of the CSV files for that test has changed (there is a different location for each test) but the location where they are expected has not (the data dir was still './target/data`.

**Comment by Khorkhe** [comment]
turns out the errors were indeed unrelated, mine were resolved with a simple sbt clean.  sorry for barging in to the thread

**Comment by laneb** [comment]
Fixed.
