### ISSUE TITLE
Error message issue when input data missing

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#854]
For a project where the input data were missing,

Here is the error message from 8d2d95de9b222592bc47aee11b72914803ae4517, which pointed out the issue.

```
Traceback (most recent call last):
  File "/data/users/bo/SMV/src/main/python/smv/smvdataset.py", line 246, in getDataFrame
    df = self.doRun(validator, known)
  File "/data/users/bo/SMV/src/main/python/smv/smvdataset.py", line 373, in doRun
    jdf = self._smvCsvFile.doRun(validator)
  File "/data/tools/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
    self.target_id, self.name)
  File "/data/tools/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
    return f(*a, **kw)
  File "/data/tools/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
    format(target_id, '.', name), value)
Py4JJavaError: An error occurred while calling o131.doRun.
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/data/users/bo/projects/RB_Retail/data/input/trnx/transaction.txt
	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:287)
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:229)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:315)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:207)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
```

Here is the error message from release 1.5.2.10
```
Traceback (most recent call last):
  File "/data/users/bo/SMV/tools/../src/main/python/scripts/runapp.py", line 19, in <module>
    app.run()
  File "/data/users/bo/SMV/src/main/python/smv/smvapp.py", line 201, in run
    self.j_smvApp.run()
  File "/data/tools/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/data/tools/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
  File "/data/tools/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o23.run.
: py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: x
	at py4j.Protocol.getReturnValue(Protocol.java:417)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:113)
	at com.sun.proxy.$Proxy27.instanceValHash(Unknown Source)
	at org.tresamigos.smv.SmvExtModulePython.instanceValHash(SmvDataSet.scala:946)
	at org.tresamigos.smv.SmvDataSet.datasetHash(SmvDataSet.scala:122)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:73)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:73)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvModuleLink$$anonfun$1.apply$mcI$sp(SmvDataSet.scala:864)
	at org.tresamigos.smv.SmvModuleLink$$anonfun$1.apply(SmvDataSet.scala:864)
	at org.tresamigos.smv.SmvModuleLink$$anonfun$1.apply(SmvDataSet.scala:864)
	at scala.Option.getOrElse(Option.scala:120)
	at org.tresamigos.smv.SmvModuleLink.instanceValHash(SmvDataSet.scala:864)
	at org.tresamigos.smv.SmvDataSet.datasetHash(SmvDataSet.scala:122)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:73)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:73)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:73)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvModuleLink$$anonfun$1.apply$mcI$sp(SmvDataSet.scala:864)
	at org.tresamigos.smv.SmvModuleLink$$anonfun$1.apply(SmvDataSet.scala:864)
	at org.tresamigos.smv.SmvModuleLink$$anonfun$1.apply(SmvDataSet.scala:864)
	at scala.Option.getOrElse(Option.scala:120)
	at org.tresamigos.smv.SmvModuleLink.instanceValHash(SmvDataSet.scala:864)
	at org.tresamigos.smv.SmvDataSet.datasetHash(SmvDataSet.scala:122)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet$$anonfun$hashOfHash$1.apply(SmvDataSet.scala:136)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:73)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.tresamigos.smv.SmvDataSet.hashOfHash$lzycompute(SmvDataSet.scala:136)
	at org.tresamigos.smv.SmvDataSet.hashOfHash(SmvDataSet.scala:135)
	at org.tresamigos.smv.SmvDataSet.verHex(SmvDataSet.scala:210)
	at org.tresamigos.smv.SmvDataSet.versionedFqn(SmvDataSet.scala:211)
	at org.tresamigos.smv.SmvDataSet.rdd(SmvDataSet.scala:204)
	at org.tresamigos.smv.SmvApp$$anonfun$generateOutputModules$1.apply(SmvApp.scala:284)
	at org.tresamigos.smv.SmvApp$$anonfun$generateOutputModules$1.apply(SmvApp.scala:284)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.tresamigos.smv.SmvApp.generateOutputModules(SmvApp.scala:284)
	at org.tresamigos.smv.SmvApp.run(SmvApp.scala:368)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
```

Since the error message here does not very helpful, I don't even know whether it is cause by the same problem or not.

**Comment by ninjapapa** [comment]
After I changed the input dir of the project, SMV 1.5.2.10 version ran successfully. It indicated that the error message of SMV 1.5.2.10 has issues.

**Comment by laneb** [comment]
At a glance, I think the problem is that the Python `SmvCsvFile` now asks the Scala `SmvCsvFile` for its `instanceValHash`, but this method doesn't print the stacktrace in case of failure. Need to add the `@with_stacktrace` decorator to this and also the `sourceCodeHash` method.

**Comment by ninjapapa** [comment]
Is this issue confirmed fixed?

**Comment by Khorkhe** [comment]
Yes, it was just merged into master. Please let me know if it's not working as it should for you
