### ISSUE TITLE
add official support for python 3.x

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#857]
The internals should already work and this might just be relaxing the check in `smv-install` (hopefully 🤞 )

**Comment by laneb** [comment]
Should the Python version for Travis CI be updated?

**Comment by jacobdr** [comment]
I think we should use a tool like tox and test both versions.

Jacob

**Comment by AliTajeldin** [comment]
For travis, I think it is as easy as adding the following to the yml file:
```
python:
  - "2.7"
  - "3.2"
```

**Comment by AliTajeldin** [comment]
Also, Travis has support for user defined matrix (you can mix and match multiple languages).  I think this is better than just adding python modules so that we can just repeat the python tests with each version and not have to re-run the scala tests.
See https://stackoverflow.com/a/44054333/7753976 for an example.

**Comment by laneb** [comment]
Based on [this issue](https://github.com/travis-ci/travis-ci/issues/4090) it doesn't appear that travis 's default build image supports combining multiple language requirements - you can test against multiple versions of a single language, but not multiple languages as needed for the Python tests. The suggestion made in that issue is to use the Trusty image which is more flexible.

**Comment by laneb** [comment]
Unfortunately, I get the following error when trying to run the Python unit tests with Python 3.5.3:
```
Spark Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -cp target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar:/Users/laneb/Library/spark/conf/:/Users/laneb/Library/spark/lib/spark-assembly-1.5.2-hadoop2.7.2.jar:/Users/laneb/Library/spark/lib/datanucleus-api-jdo-3.2.6.jar:/Users/laneb/Library/spark/lib/datanucleus-core-3.2.10.jar:/Users/laneb/Library/spark/lib/datanucleus-rdbms-3.2.9.jar -Xms1g -Xmx1g org.apache.spark.deploy.SparkSubmit --conf spark.driver.extraClassPath=target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar --jars target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar, /Users/laneb/twine/SMV/tools/../src/main/python/scripts/runtests.py
========================================
Traceback (most recent call last):
  File "/Users/laneb/twine/SMV/tools/../src/main/python/scripts/runtests.py", line 16, in <module>
    from test_support.testconfig import TestConfig
  File "/Users/laneb/twine/SMV/src/main/python/test_support/testconfig.py", line 18, in <module>
    from smv.smvapp import SmvApp
  File "/Users/laneb/twine/SMV/src/main/python/smv/__init__.py", line 2, in <module>
    from smvdataset import *
ImportError: No module named 'smvdataset'
java.lang.IllegalStateException: pytest failed
	at $0a850d546b790671ed61$$anonfun$$sbtdef$1.apply(/Users/laneb/twine/SMV/build.sbt:43)
	at $0a850d546b790671ed61$$anonfun$$sbtdef$1.apply(/Users/laneb/twine/SMV/build.sbt:40)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:pytest) java.lang.IllegalStateException: pytest failed
[error] Total time: 3 s, completed Jun 8, 2017 3:17:39 PM
```

**Comment by jacobdr** [comment]
It's the relative import issue, no?

https://stackoverflow.com/questions/12172791/changes-in-import-statement-python3

Jacob

**Comment by laneb** [comment]
Must be. Wasn't aware of this.

**Comment by laneb** [comment]
Also need to remove `basestring` from the codebase: http://www.rfk.id.au/blog/entry/preparing-pyenchant-for-python-3/

**Comment by AliTajeldin** [comment]
@laneb TravisCI does not support multiple languages as you pointed out in the SO link.  But they added support for "matrix" config that does allow you to specify a test matrix with multiple languages.  See link in my reply above.

**Comment by laneb** [comment]
All tests now passing with Python 3.5.3.

**Comment by laneb** [comment]
To summarize, the changes made here are

1. Fixes for various Python3 incompatibilities in our code, including
  - Changes in the API of `binascii` and `inspect`
  - Change to the builtin `map` function and `print` keyword, and removal of builtin `basestring` type
  - The relative import problem mentioned above

2. Addition of a `tox.ini` for running tests against multiple Pythons with `tox`. Note that while this could hypothetically be used to run `tox` locally, it is not currently intended for that purpose. Per conversation with @AliTajeldin there is no need anticipated for that use case.

3. Revamped `.travis.yml` which runs Scala unit tests with `sbt` and runs Python unit tests and the integration tests with `tox`

Is there anything else needed?

**Comment by AliTajeldin** [comment]
Looks good. closing
