### ISSUE TITLE
Integration test failed on Py3.5 + 2.1 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#901]
Error message:
```
Starting Py4j callback server on port 25334
Traceback (most recent call last):
  File "/home/travis/build/TresAmigosSD/SMV/src/main/python/smv/stacktrace_mixin.py", line 20, in catch_errs
    res = func_needing_stacktrace(*pargs, **kwargs)
  File "/home/travis/build/TresAmigosSD/SMV/src/main/python/smv/datasetrepo.py", line 57, in loadDataSet
    ds = for_name(fqn)(self.smvApp)
  File "/home/travis/build/TresAmigosSD/SMV/src/main/python/smv/utils.py", line 29, in for_name
    mod = __import__(modname)
ImportError: No module named 'org.tresamigos'
Traceback (most recent call last):
  File "/home/travis/build/TresAmigosSD/SMV/tools/../src/main/python/scripts/runapp.py", line 19, in <module>
    app.run()
  File "/home/travis/build/TresAmigosSD/SMV/src/main/python/smv/smvapp.py", line 205, in run
    self.j_smvApp.run()
  File "/home/travis/build/TresAmigosSD/SMV/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/home/travis/build/TresAmigosSD/SMV/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/home/travis/build/TresAmigosSD/SMV/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o31.run.
: org.tresamigos.smv.SmvRuntimeException: SmvDataSet mod:org.tresamigos.smvtest.test5.modules.M1 not found
	at org.tresamigos.smv.DataSetResolver.org$tresamigos$smv$DataSetResolver$$findDataSetInRepo(DataSetResolver.scala:126)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1$$anonfun$apply$1.apply(DataSetResolver.scala:58)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1$$anonfun$apply$1.apply(DataSetResolver.scala:52)
	at scala.Option.getOrElse(Option.scala:121)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:52)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:45)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.tresamigos.smv.DataSetResolver.loadDataSet(DataSetResolver.scala:45)
	at org.tresamigos.smv.SmvExtModule.resolve(SmvDataSet.scala:952)
	at org.tresamigos.smv.DataSetResolver$$anonfun$resolveDataSet$1.apply(DataSetResolver.scala:81)
	at org.tresamigos.smv.DataSetResolver$$anonfun$resolveDataSet$1.apply(DataSetResolver.scala:79)
	at scala.Option.getOrElse(Option.scala:121)
	at org.tresamigos.smv.DataSetResolver.resolveDataSet(DataSetResolver.scala:79)
	at org.tresamigos.smv.SmvDataSet$$anonfun$resolve$1.apply(SmvDataSet.scala:84)
	at org.tresamigos.smv.SmvDataSet$$anonfun$resolve$1.apply(SmvDataSet.scala:84)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.tresamigos.smv.SmvDataSet.resolve(SmvDataSet.scala:84)
	at org.tresamigos.smv.DataSetResolver$$anonfun$resolveDataSet$1.apply(DataSetResolver.scala:81)
	at org.tresamigos.smv.DataSetResolver$$anonfun$resolveDataSet$1.apply(DataSetResolver.scala:79)
	at scala.Option.getOrElse(Option.scala:121)
	at org.tresamigos.smv.DataSetResolver.resolveDataSet(DataSetResolver.scala:79)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1$$anonfun$apply$1.apply(DataSetResolver.scala:60)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1$$anonfun$apply$1.apply(DataSetResolver.scala:52)
	at scala.Option.getOrElse(Option.scala:121)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:52)
	at org.tresamigos.smv.DataSetResolver$$anonfun$loadDataSet$1.apply(DataSetResolver.scala:45)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.tresamigos.smv.DataSetResolver.loadDataSet(DataSetResolver.scala:45)
	at org.tresamigos.smv.TX.load(Transaction.scala:33)
	at org.tresamigos.smv.TX.allDataSets(Transaction.scala:45)
	at org.tresamigos.smv.TX.allOutputModules(Transaction.scala:48)
	at org.tresamigos.smv.DataSetMgr$$anonfun$modulesToRun$1.apply(DataSetMgr.scala:52)
	at org.tresamigos.smv.DataSetMgr$$anonfun$modulesToRun$1.apply(DataSetMgr.scala:49)
	at org.tresamigos.smv.DataSetMgr.withTX(DataSetMgr.scala:43)
	at org.tresamigos.smv.DataSetMgr.modulesToRun(DataSetMgr.scala:49)
	at org.tresamigos.smv.SmvApp.modulesToRun$lzycompute(SmvApp.scala:350)
	at org.tresamigos.smv.SmvApp.modulesToRun(SmvApp.scala:343)
	at org.tresamigos.smv.SmvApp.run(SmvApp.scala:369)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

The error was recreated on local max machine also.

**Comment by ninjapapa** [comment]
This issue is related to both Python 3.4+ and Spark 2.1. The reason roughly is like this,

* In Python 3.4+, __import__ uses cached `sys.modules`
* IN Python 3.4+, parent modules are automatically imported when child module get imported
* Spark 2.1's pyspark code imported something starts with `org` (actually in the jar file)

So `org` is in `sys.modules` and when we call `__import__` on `org.tresamegos....` it will try to find `tresamegos` in `org` module.

**Comment by ninjapapa** [comment]
There is an easy fix, just delete 'org' from `sys.modules` when initiate `DataSetRepoFactory`.
However I do think we need to review the "import" mechanism of Python 3.4+ and our dynamic import code to make sure that we can cover potential issues like this in the future.

I will create a PR to apply the simply fix.

**Comment by ninjapapa** [comment]
Applied simple fix in PR #906

**Comment by ninjapapa** [comment]
According to
https://docs.python.org/3/reference/import.html

Python now supporting both `regular package` and `namespace package`. I thing the issue we are encounter is caused by the mix of those 2, where `org` from the spark-core....jar is loaded as a `namespace package` and, `org.tresamegos` is still a `regular package`.

**Comment by laneb** [comment]
Glancing over that doc and [this PEP](https://www.python.org/dev/peps/pep-0420/) on implicit namespace packages, it's not clear to me why Python would find anything inside of (or look inside of) a jar. Can you point to where in the pyspark code that import happens?

**Comment by laneb** [comment]
This is also confusing because the points you described 

> In Python 3.4+, import uses cached sys.modules
> IN Python 3.4+, parent modules are automatically imported when child module get imported

are also true of Python <3.4. If a package with a name like `org.*` was being imported by pyspark in Python 2.7, I would expect the same problem. Does this problem only occur for Python >3.4?

**Comment by ninjapapa** [comment]
No, I can't figure out how the jar got there. 
What I did is I printed out the '__path__' attribute of module 'org', and it shows the path is in a jar.

**Comment by ninjapapa** [comment]
It is only in 3.5. Since the 'org' dir in a jar has no '__init__.py' so in 2.7 it will not be imported as a module.

**Comment by laneb** [comment]
The problematic import turns out to be the import of `pickle` in Spark's `python/pyspark/cloudpickle.py`. This problem can easily be replicated in the Python shell by adding the Spark jar to `sys.path` and importing `pickle`. I still don't understand

- why importing `pickle` imports the `org` as a namespace package
- why the Spark jar is in the Python path

but I think those are outside the scope of this issue. Per @AliTajeldin it is not very clean to explicitly delete the `org` module and we shouldn't try to manage this bug in `pyspark`. Instead we should change the name of the integration test modules so that they can be imported without conflict.

**Comment by laneb** [comment]
I will make the a PR to add this change to master so that the tests for all branches will be in sync.

**Comment by ninjapapa** [comment]
Should we document this PySpark bug - do not using `org` as the top name base in project?

**Comment by laneb** [comment]
Where would be a good place to document this?

**Comment by ninjapapa** [comment]
Known issues?

**Comment by laneb** [comment]
Why didn't I think of that...
